### ISSUE TITLE
Get signoff from Zach for matmul blog post

### ISSUE THREAD

**Issue by LegNeato** [Rust-GPU/rust-gpu.github.io#20]
@zanussbaum, I reimplemented your great [blog post](https://www.nuss-and-bolts.com/p/optimizing-a-webgpu-matmul-kernel) using Rust GPU. It is currently in draft so we can iterate a bit.

I'd like your sign-off that what we did is cool with you. You can check out the code and run it locally to see the draft, or look at it on GitHub:

https://github.com/Rust-GPU/rust-gpu.github.io/blob/main/blog/2024-11-21-optimizing-matrix-mul/index.md

If you'd rather us not publish our reimplementation, no worries...just say so!

Thanks for taking the time 🍻

**Comment by LegNeato** [comment]
Awesome, I'll make your name a link...which do you prefer @zanussbaum ?

I didn't put any perf numbers in there because I have a different machine and I was seeing some wonky stuff. That's one of the things I want us Rust GPU maintainers to dig into now that the code landed in the repo and others can take a look.

**Comment by zanussbaum** [comment]
cool yeah I'd be interested in comparing what the compiled kernels look like compared to WGSL/Surfgrad on the same machines! 

Twitter is perfect thanks @LegNeato
